// priority: 0

ItemEvents.tooltip(event => {
	event.add(['create:limestone', 'create:honey', 'create:honey_bucket'], ['§7Limestone §8can be generated by §7liquid Honey §8interacting with §7lava§8, akin to a cobblestone generator with the water replaced.', '§8..How sweet of it.']);
	event.add(['create:scoria', 'create:chocolate', 'create:chocolate_bucket'], ['§7Scoria §8can be generated by §7liquid Chocolate §8interacting with §7lava§8, akin to a cobblestone generator with the water replaced.', '§8..I wouldn\'t taste it.']);
	event.add(['minecraft:blackstone', 'create_enchantment_industry:ink', 'create_enchantment_industry:ink_bucket'], ['§7Blackstone §8can be generated by §7liquid Ink §8interacting with §7lava§8, akin to a cobblestone generator with the water replaced.', '§8..Great with pasta!']);
})